### ISSUE TITLE
TTGO T7 V1.4 Mini32 build fails on Arduino IDE 

### ISSUE THREAD

**Issue by apcameron** [jscrane/UK101#24]
WARNING: library PS2KeyRaw claims to run on avr, sam architecture(s) and may be incompatible with your current board which runs on esp32 architecture(s).
c:\Users\andrew\Documents\Arduino\libraries\r65emu\src\timed.cpp: In function 'void timer_create(unsigned int, handler_t)':
c:\Users\andrew\Documents\Arduino\libraries\r65emu\src\timed.cpp:38:39: error: too many arguments to function 'hw_timer_t* timerBegin(uint32_t)'
   38 |         hw_timer_t *timer = timerBegin(3, 80, true);    // prescaler of 80
      |                             ~~~~~~~~~~^~~~~~~~~~~~~
In file included from C:\Users\andrew\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.5\cores\esp32/esp32-hal.h:84,
                 from C:\Users\andrew\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.5\cores\esp32/Arduino.h:36,
                 from c:\Users\andrew\Documents\Arduino\libraries\r65emu\src\timed.cpp:1:
C:\Users\andrew\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.5\cores\esp32/esp32-hal-timer.h:35:13: note: declared here
   35 | hw_timer_t *timerBegin(uint32_t frequency);
      |             ^~~~~~~~~~
c:\Users\andrew\Documents\Arduino\libraries\r65emu\src\timed.cpp:39:29: error: too many arguments to function 'void timerAttachInterrupt(hw_timer_t*, void (*)())'
   39 |         timerAttachInterrupt(timer, handler, true);
      |         ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
C:\Users\andrew\AppData\Local\Arduino15\packages\esp32\hardware\esp32\3.0.5\cores\esp32/esp32-hal-timer.h:50:6: note: declared here
   50 | void timerAttachInterrupt(hw_timer_t *timer, void (*userFunc)(void));
      |      ^~~~~~~~~~~~~~~~~~~~
c:\Users\andrew\Documents\Arduino\libraries\r65emu\src\timed.cpp:40:9: error: 'timerAlarmWrite' was not declared in this scope; did you mean 'timerWrite'?
   40 |         timerAlarmWrite(timer, 1000000 / freq, true);
      |         ^~~~~~~~~~~~~~~
      |         timerWrite
c:\Users\andrew\Documents\Arduino\libraries\r65emu\src\timed.cpp:41:9: error: 'timerAlarmEnable' was not declared in this scope; did you mean 'timerAlarm'?
   41 |         timerAlarmEnable(timer);
      |         ^~~~~~~~~~~~~~~~
      |         timerAlarm

exit status 1

Compilation error: exit status 1

**Comment by jscrane** [comment]
Hi Andrew,
It looks as if you're using version 3.0.5 of the esp32 Arduino core. I haven't gotten around to supporting that version yet. (Last time I looked the FabGL library didn't compile on version 3.x and that's required for the TTGO board.)

If you can, please try with version 2.0.x of the esp32 core. (I'm using 2.0.17.)

Cheers,
Steve

**Comment by apcameron** [comment]
Thank you. Downgrading to the version you suggested solved the problem.
